---
latitude: 40.755
longitude: -73.96885
map_zoom: 12
name: Cozy Studio
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 250 East 50th Street
  street2: ''
  state: New York
  city: New York
  country: United States
  zip_code: '10022'
_hotel_id: COZ108
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
